trigger

diff --git a/.github/workflows/release_zango.yml b/.github/workflows/release_zango.yml
--- a/.github/workflows/release_zango.yml
+++ b/.github/workflows/release_zango.yml
@@ -23,8 +23,8 @@ jobs:
       id: get_version
       run: |
         set -e
-        VERSION=$(grep -oE "\d+\.\d+\.\d+" CHANGELOG.md | head -n 3 | tail -n 1)
-        echo $?
+        VERSION=$(grep -oE "[0-9]+\.[0-9]+\.[0-9]+" CHANGELOG.md | sed -n '3p' || echo "Not found")
+        echo "VERSION=$VERSION"
         echo "VERSION=$VERSION" >> $GITHUB_ENV
 
     - name: Set up Docker Buildx
